name: 'SimpleCov coverage difference with parsing from my resultset'
description: 'Creates a comment in the pull-request comparing two SimpleCov resultset files.'
author: Artsiom Harashchenia
inputs:
  base-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the base branch'
    required: true
  head-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the head branch'
    required: true
  token:
    description: 'Github generated token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
